<?php

/**
 * GetCorporationsCorporationIdStructures200Ok
 *
 * PHP version 7
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
namespace WordPress\Plugin\EveOnlineIntelTool\Libs\Swagger\Client\Model;

use \ArrayAccess;
use \WordPress\Plugin\EveOnlineIntelTool\Libs\Swagger\Client\ObjectSerializer;

/**
 * GetCorporationsCorporationIdStructures200Ok Class Doc Comment
 *
 * @category Class
 * @description 200 ok object
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GetCorporationsCorporationIdStructures200Ok implements ModelInterface, ArrayAccess {

	const DISCRIMINATOR = null;

	/**
	 * The original name of the model.
	 *
	 * @var string
	 */
	protected static $swaggerModelName = 'get_corporations_corporation_id_structures_200_ok';

	/**
	 * Array of property to type mappings. Used for (de)serialization
	 *
	 * @var string[]
	 */
	protected static $swaggerTypes = [
		'structure_id' => 'int',
		'type_id' => 'int',
		'corporation_id' => 'int',
		'system_id' => 'int',
		'profile_id' => 'int',
		'current_vul' => '\WordPress\Plugin\EveOnlineIntelTool\Libs\Swagger\Client\Model\GetCorporationsCorporationIdStructuresCurrentVul[]',
		'next_vul' => '\WordPress\Plugin\EveOnlineIntelTool\Libs\Swagger\Client\Model\GetCorporationsCorporationIdStructuresNextVul[]',
		'fuel_expires' => '\DateTime',
		'services' => '\WordPress\Plugin\EveOnlineIntelTool\Libs\Swagger\Client\Model\GetCorporationsCorporationIdStructuresService[]',
		'state_timer_start' => '\DateTime',
		'state_timer_end' => '\DateTime',
		'unanchors_at' => '\DateTime'
	];

	/**
	 * Array of property to format mappings. Used for (de)serialization
	 *
	 * @var string[]
	 */
	protected static $swaggerFormats = [
		'structure_id' => 'int64',
		'type_id' => 'int32',
		'corporation_id' => 'int32',
		'system_id' => 'int32',
		'profile_id' => 'int32',
		'current_vul' => null,
		'next_vul' => null,
		'fuel_expires' => 'date-time',
		'services' => null,
		'state_timer_start' => 'date-time',
		'state_timer_end' => 'date-time',
		'unanchors_at' => 'date-time'
	];

	/**
	 * Array of property to type mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function swaggerTypes() {
		return self::$swaggerTypes;
	}

	/**
	 * Array of property to format mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function swaggerFormats() {
		return self::$swaggerFormats;
	}

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @var string[]
	 */
	protected static $attributeMap = [
		'structure_id' => 'structure_id',
		'type_id' => 'type_id',
		'corporation_id' => 'corporation_id',
		'system_id' => 'system_id',
		'profile_id' => 'profile_id',
		'current_vul' => 'current_vul',
		'next_vul' => 'next_vul',
		'fuel_expires' => 'fuel_expires',
		'services' => 'services',
		'state_timer_start' => 'state_timer_start',
		'state_timer_end' => 'state_timer_end',
		'unanchors_at' => 'unanchors_at'
	];

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @var string[]
	 */
	protected static $setters = [
		'structure_id' => 'setStructureId',
		'type_id' => 'setTypeId',
		'corporation_id' => 'setCorporationId',
		'system_id' => 'setSystemId',
		'profile_id' => 'setProfileId',
		'current_vul' => 'setCurrentVul',
		'next_vul' => 'setNextVul',
		'fuel_expires' => 'setFuelExpires',
		'services' => 'setServices',
		'state_timer_start' => 'setStateTimerStart',
		'state_timer_end' => 'setStateTimerEnd',
		'unanchors_at' => 'setUnanchorsAt'
	];

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @var string[]
	 */
	protected static $getters = [
		'structure_id' => 'getStructureId',
		'type_id' => 'getTypeId',
		'corporation_id' => 'getCorporationId',
		'system_id' => 'getSystemId',
		'profile_id' => 'getProfileId',
		'current_vul' => 'getCurrentVul',
		'next_vul' => 'getNextVul',
		'fuel_expires' => 'getFuelExpires',
		'services' => 'getServices',
		'state_timer_start' => 'getStateTimerStart',
		'state_timer_end' => 'getStateTimerEnd',
		'unanchors_at' => 'getUnanchorsAt'
	];

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @return array
	 */
	public static function attributeMap() {
		return self::$attributeMap;
	}

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @return array
	 */
	public static function setters() {
		return self::$setters;
	}

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @return array
	 */
	public static function getters() {
		return self::$getters;
	}

	/**
	 * The original name of the model.
	 *
	 * @return string
	 */
	public function getModelName() {
		return self::$swaggerModelName;
	}

	/**
	 * Associative array for storing property values
	 *
	 * @var mixed[]
	 */
	protected $container = [];

	/**
	 * Constructor
	 *
	 * @param mixed[] $data Associated array of property values
	 *                      initializing the model
	 */
	public function __construct(array $data = null) {
		$this->container['structure_id'] = isset($data['structure_id']) ? $data['structure_id'] : null;
		$this->container['type_id'] = isset($data['type_id']) ? $data['type_id'] : null;
		$this->container['corporation_id'] = isset($data['corporation_id']) ? $data['corporation_id'] : null;
		$this->container['system_id'] = isset($data['system_id']) ? $data['system_id'] : null;
		$this->container['profile_id'] = isset($data['profile_id']) ? $data['profile_id'] : null;
		$this->container['current_vul'] = isset($data['current_vul']) ? $data['current_vul'] : null;
		$this->container['next_vul'] = isset($data['next_vul']) ? $data['next_vul'] : null;
		$this->container['fuel_expires'] = isset($data['fuel_expires']) ? $data['fuel_expires'] : null;
		$this->container['services'] = isset($data['services']) ? $data['services'] : null;
		$this->container['state_timer_start'] = isset($data['state_timer_start']) ? $data['state_timer_start'] : null;
		$this->container['state_timer_end'] = isset($data['state_timer_end']) ? $data['state_timer_end'] : null;
		$this->container['unanchors_at'] = isset($data['unanchors_at']) ? $data['unanchors_at'] : null;
	}

	/**
	 * Show all the invalid properties with reasons.
	 *
	 * @return array invalid properties with reasons
	 */
	public function listInvalidProperties() {
		$invalidProperties = [];

		if($this->container['structure_id'] === null) {
			$invalidProperties[] = "'structure_id' can't be null";
		}
		if($this->container['type_id'] === null) {
			$invalidProperties[] = "'type_id' can't be null";
		}
		if($this->container['corporation_id'] === null) {
			$invalidProperties[] = "'corporation_id' can't be null";
		}
		if($this->container['system_id'] === null) {
			$invalidProperties[] = "'system_id' can't be null";
		}
		if($this->container['profile_id'] === null) {
			$invalidProperties[] = "'profile_id' can't be null";
		}
		if($this->container['current_vul'] === null) {
			$invalidProperties[] = "'current_vul' can't be null";
		}
		if($this->container['next_vul'] === null) {
			$invalidProperties[] = "'next_vul' can't be null";
		}
		return $invalidProperties;
	}

	/**
	 * Validate all the properties in the model
	 * return true if all passed
	 *
	 * @return bool True if all properties are valid
	 */
	public function valid() {

		if($this->container['structure_id'] === null) {
			return false;
		}
		if($this->container['type_id'] === null) {
			return false;
		}
		if($this->container['corporation_id'] === null) {
			return false;
		}
		if($this->container['system_id'] === null) {
			return false;
		}
		if($this->container['profile_id'] === null) {
			return false;
		}
		if($this->container['current_vul'] === null) {
			return false;
		}
		if($this->container['next_vul'] === null) {
			return false;
		}
		return true;
	}

	/**
	 * Gets structure_id
	 *
	 * @return int
	 */
	public function getStructureId() {
		return $this->container['structure_id'];
	}

	/**
	 * Sets structure_id
	 *
	 * @param int $structure_id The Item ID of the structure
	 *
	 * @return $this
	 */
	public function setStructureId($structure_id) {
		$this->container['structure_id'] = $structure_id;

		return $this;
	}

	/**
	 * Gets type_id
	 *
	 * @return int
	 */
	public function getTypeId() {
		return $this->container['type_id'];
	}

	/**
	 * Sets type_id
	 *
	 * @param int $type_id The type id of the structure
	 *
	 * @return $this
	 */
	public function setTypeId($type_id) {
		$this->container['type_id'] = $type_id;

		return $this;
	}

	/**
	 * Gets corporation_id
	 *
	 * @return int
	 */
	public function getCorporationId() {
		return $this->container['corporation_id'];
	}

	/**
	 * Sets corporation_id
	 *
	 * @param int $corporation_id ID of the corporation that owns the structure
	 *
	 * @return $this
	 */
	public function setCorporationId($corporation_id) {
		$this->container['corporation_id'] = $corporation_id;

		return $this;
	}

	/**
	 * Gets system_id
	 *
	 * @return int
	 */
	public function getSystemId() {
		return $this->container['system_id'];
	}

	/**
	 * Sets system_id
	 *
	 * @param int $system_id The solar system the structure is in
	 *
	 * @return $this
	 */
	public function setSystemId($system_id) {
		$this->container['system_id'] = $system_id;

		return $this;
	}

	/**
	 * Gets profile_id
	 *
	 * @return int
	 */
	public function getProfileId() {
		return $this->container['profile_id'];
	}

	/**
	 * Sets profile_id
	 *
	 * @param int $profile_id The id of the ACL profile for this citadel
	 *
	 * @return $this
	 */
	public function setProfileId($profile_id) {
		$this->container['profile_id'] = $profile_id;

		return $this;
	}

	/**
	 * Gets current_vul
	 *
	 * @return \WordPress\Plugin\EveOnlineIntelTool\Libs\Swagger\Client\Model\GetCorporationsCorporationIdStructuresCurrentVul[]
	 */
	public function getCurrentVul() {
		return $this->container['current_vul'];
	}

	/**
	 * Sets current_vul
	 *
	 * @param \WordPress\Plugin\EveOnlineIntelTool\Libs\Swagger\Client\Model\GetCorporationsCorporationIdStructuresCurrentVul[] $current_vul This week's vulnerability windows, Monday is day 0
	 *
	 * @return $this
	 */
	public function setCurrentVul($current_vul) {
		$this->container['current_vul'] = $current_vul;

		return $this;
	}

	/**
	 * Gets next_vul
	 *
	 * @return \WordPress\Plugin\EveOnlineIntelTool\Libs\Swagger\Client\Model\GetCorporationsCorporationIdStructuresNextVul[]
	 */
	public function getNextVul() {
		return $this->container['next_vul'];
	}

	/**
	 * Sets next_vul
	 *
	 * @param \WordPress\Plugin\EveOnlineIntelTool\Libs\Swagger\Client\Model\GetCorporationsCorporationIdStructuresNextVul[] $next_vul Next week's vulnerability windows, Monday is day 0
	 *
	 * @return $this
	 */
	public function setNextVul($next_vul) {
		$this->container['next_vul'] = $next_vul;

		return $this;
	}

	/**
	 * Gets fuel_expires
	 *
	 * @return \DateTime
	 */
	public function getFuelExpires() {
		return $this->container['fuel_expires'];
	}

	/**
	 * Sets fuel_expires
	 *
	 * @param \DateTime $fuel_expires Date on which the structure will run out of fuel
	 *
	 * @return $this
	 */
	public function setFuelExpires($fuel_expires) {
		$this->container['fuel_expires'] = $fuel_expires;

		return $this;
	}

	/**
	 * Gets services
	 *
	 * @return \WordPress\Plugin\EveOnlineIntelTool\Libs\Swagger\Client\Model\GetCorporationsCorporationIdStructuresService[]
	 */
	public function getServices() {
		return $this->container['services'];
	}

	/**
	 * Sets services
	 *
	 * @param \WordPress\Plugin\EveOnlineIntelTool\Libs\Swagger\Client\Model\GetCorporationsCorporationIdStructuresService[] $services Contains a list of service upgrades, and their state
	 *
	 * @return $this
	 */
	public function setServices($services) {
		$this->container['services'] = $services;

		return $this;
	}

	/**
	 * Gets state_timer_start
	 *
	 * @return \DateTime
	 */
	public function getStateTimerStart() {
		return $this->container['state_timer_start'];
	}

	/**
	 * Sets state_timer_start
	 *
	 * @param \DateTime $state_timer_start Date at which the structure entered it's current state
	 *
	 * @return $this
	 */
	public function setStateTimerStart($state_timer_start) {
		$this->container['state_timer_start'] = $state_timer_start;

		return $this;
	}

	/**
	 * Gets state_timer_end
	 *
	 * @return \DateTime
	 */
	public function getStateTimerEnd() {
		return $this->container['state_timer_end'];
	}

	/**
	 * Sets state_timer_end
	 *
	 * @param \DateTime $state_timer_end Date at which the structure will move to it's next state
	 *
	 * @return $this
	 */
	public function setStateTimerEnd($state_timer_end) {
		$this->container['state_timer_end'] = $state_timer_end;

		return $this;
	}

	/**
	 * Gets unanchors_at
	 *
	 * @return \DateTime
	 */
	public function getUnanchorsAt() {
		return $this->container['unanchors_at'];
	}

	/**
	 * Sets unanchors_at
	 *
	 * @param \DateTime $unanchors_at Date at which the structure will unanchor
	 *
	 * @return $this
	 */
	public function setUnanchorsAt($unanchors_at) {
		$this->container['unanchors_at'] = $unanchors_at;

		return $this;
	}

	/**
	 * Returns true if offset exists. False otherwise.
	 *
	 * @param integer $offset Offset
	 *
	 * @return boolean
	 */
	public function offsetExists($offset) {
		return isset($this->container[$offset]);
	}

	/**
	 * Gets offset.
	 *
	 * @param integer $offset Offset
	 *
	 * @return mixed
	 */
	public function offsetGet($offset) {
		return isset($this->container[$offset]) ? $this->container[$offset] : null;
	}

	/**
	 * Sets value based on offset.
	 *
	 * @param integer $offset Offset
	 * @param mixed   $value  Value to be set
	 *
	 * @return void
	 */
	public function offsetSet($offset, $value) {
		if(is_null($offset)) {
			$this->container[] = $value;
		} else {
			$this->container[$offset] = $value;
		}
	}

	/**
	 * Unsets offset.
	 *
	 * @param integer $offset Offset
	 *
	 * @return void
	 */
	public function offsetUnset($offset) {
		unset($this->container[$offset]);
	}

	/**
	 * Gets the string presentation of the object
	 *
	 * @return string
	 */
	public function __toString() {
		if(defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
			return json_encode(
				ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT
			);
		}

		return json_encode(ObjectSerializer::sanitizeForSerialization($this));
	}

}
